"""empty message

Revision ID: e56ef15d0b77
Revises: 88e1b8dd1925
Create Date: 2019-03-13 13:21:49.132301

"""

# revision identifiers, used by Alembic.
revision = 'e56ef15d0b77'
down_revision = '88e1b8dd1925'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restful_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('testtable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testtable',
    sa.Column('img_name', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('img_url', mysql.VARCHAR(length=1000), nullable=True),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('restful_user')
    # ### end Alembic commands ###
